apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
type: Opaque
data:
#  mongo-user: aWtvZW1iZQ==
  mongo-user: cm9vdHVzZXI=
#  mongo-password: QnVyYWtiZWJldDQ3NTEu
  mongo-password: cm9vdHBhc3M=

